apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
  namespace: payment-service-ns
type: Opaque
stringData:
  DB_PASSWORD: Root$1234
  JWT_SECRET: your-super-secret-jwt-key-change-in-production
  RAZORPAY_KEY_ID: rzp_test_2JnJUPRtxgUYQx
  RAZORPAY_KEY_SECRET: mTLE5MZvw7XySYn6RQvgxYSX
