apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: product-service-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: ayushsoni7777/micro_mart:product-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
              name: http
          envFrom:
            - configMapRef:
                name: product-service-config
            - secretRef:
                name: product-service-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 15
