apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
  namespace: inventory-service-ns
data:
  MONGODB_URI: mongodb://mongodb.mongodb-ns.svc.cluster.local:27017/inventorymart_db
  PORT: "3005"
  NODE_ENV: development
  PRODUCT_SERVICE_URL: http://product-service.product-service-ns.svc.cluster.local:3002/api/products
