apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: inventory-service-ns
spec:
  selector:
    app: inventory-service
  ports:
    - port: 3005
      targetPort: 3005
      name: http
