apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: notification-service-ns
data:
  MONGODB_URI: mongodb://mongodb.mongodb-ns.svc.cluster.local:27017/notificationmart_db
  PORT: "3004"
  NODE_ENV: development
  KAFKA_CLIENT_ID: notification-service
  KAFKA_BROKERS: kafka.kafka-ns.svc.cluster.local:9092
  KAFKA_GROUP_ID: notification-service-group
  KAFKA_TOPIC_ORDER_EVENTS: order-events
