apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: notification-service-ns
spec:
  selector:
    app: notification-service
  ports:
    - port: 3004
      targetPort: 3004
      name: http
