apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: order-service-ns
data:
  DB_HOST: postgres.postgres-ns.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: ordermart_db
  DB_USER: root
  PORT: "3003"
  NODE_ENV: development
  NOTIFICATION_SERVICE_URL: http://notification-service.notification-service-ns.svc.cluster.local:3004
  INVENTORY_SERVICE_URL: http://inventory-service.inventory-service-ns.svc.cluster.local:3005
  PRODUCT_SERVICE_URL: http://product-service.product-service-ns.svc.cluster.local:3002
  KAFKA_CLIENT_ID: order-service
  KAFKA_BROKERS: kafka.kafka-ns.svc.cluster.local:9092
  KAFKA_TOPIC_ORDER_EVENTS: order-events
