apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: order-service-ns
type: Opaque
stringData:
  DB_PASSWORD: Root$1234
  JWT_SECRET: your-super-secret-jwt-key-change-in-production
