apiVersion: v1
kind: Service
metadata:
  name: reviews-service
  namespace: reviews-service-ns
spec:
  selector:
    app: reviews-service
  ports:
    - port: 3006
      targetPort: 3006
      name: http
