apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: user-service-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ayushsoni7777/micro_mart:user-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
              name: http
          envFrom:
            - configMapRef:
                name: user-service-config
            - secretRef:
                name: user-service-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 15
